### PR TITLE
Improve readme

### PR DESCRIPTION
**Pull request by Ndpnt**

### CODE REVIEW

**Comment by MattiSG** [comment]
Why delete the French description? 😯

**Comment by Ndpnt** [comment]
Because the French description was only a subpart of the full documentation and I think it makes documentation harder to maintain. So I prefer a complete documentation in one language instead of one and half documentation in two languages.

**Comment by MattiSG** [comment]
https://github.com/betagouv/beta.gouv.fr/wiki/Développement-logiciel#documentation :wink:

**Comment by Ndpnt** [comment]
Okay 🙂. I will revert my commit

Le lun. 22 juil. 2019 à 07:55, Matti Schneider <notifications@github.com> a
écrit :

**Comment by MattiSG** [comment]
Or just add a short paragraph back in French ;)

**Pull request merged**
